### ISSUE TITLE
Where are `brew` ENV vars explained in the docs?

### ISSUE THREAD

**Issue by vfonic** [Homebrew/brew.sh#723]
# Mini rant

(skip to problem below if you want)

I was just reading [this HN thread](https://news.ycombinator.com/item?id=29079096) and I'm having similar issues like the op. In my opinion (and it seems like I'm not the only one), Homebrew updates too much without asking for confirmation.

This in turn breaks things even though it's done in a good faith. And it's sooo complicated to install the previously working combination of packages. You "have to" install the latest package update. This is great for the end user, for someone who wants to install and use some app, like from the App Store. But there are plenty of Homebrew users who are power users aka developers and they might want to install specific software versions. For one: because those software versions used to work together just fine. Two, it's always good to have a stable system.

# Problem

I saw in that HN thread people mentioning some ENV vars that I can set in my shell. I went to Homebrew homepage, but I couldn't find any mention of those. Even if they are on the page, maybe they should be more visible?

Thanks for all your hard work!
Viktor

**Comment by MikeMcQuaid** [comment]
> Mini rant

Please don't post rants on our issue tracker.

> Homebrew updates too much without asking for confirmation.

I cannot think of a way for asking for confirmation without breaking all existing scripts that assume we don't ask for confirmation. We could add (another) option for this but: the same people who complain about the lack of confirmation seem to complain about being unable to find these options.

> You "have to" install the latest package update.

That's because we only support the latest version. There are of course ways to not install the latest version but: we don't support them.

> But there are plenty of Homebrew users who are power users aka developers and they might want to install specific software versions.

You can do this. You just can't get help from us when it doesn't work. We're also not going to install things we know to be broken and untested.

> I saw in that HN thread people mentioning some ENV vars that I can set in my shell. I went to Homebrew homepage, but I couldn't find any mention of those. Even if they are on the page, maybe they should be more visible?

"Further Documentation" > "`brew` man-page (command documentation)" (at the top of the page) > "Environment": https://docs.brew.sh/Manpage#environment
